/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package program.penjualan.mebel;

import javax.swing.table.TableColumn;

/**
 *
 * @author User ID
 */
public class Frame_penjualan_mebel extends javax.swing.JFrame {
    double nama,harga,jmlhjual,total;
    long hargaProduk1,hargaProduk2,hargaProduk3,hargaProduk4,hargaAkhir;
    String kodeJenis,merk,jenis,Jenis1,Jenis2,Jenis3,Jenis4,garansi,kondisi,kodeBahan,kodeUnit;
    int a=0;
    Model_penyimpanan penjualan = new Model_penyimpanan();

    /**
     * Creates new form Frame_penjualan_laptop
     */
    public Frame_penjualan_mebel() {
        initComponents();
        tblBarang.setModel(penjualan.getTabel());
        
        TableColumn column;
        tblBarang.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF); 
        column = tblBarang.getColumnModel().getColumn(0); 
        column.setPreferredWidth(50);
        column = tblBarang.getColumnModel().getColumn(1); 
        column.setPreferredWidth(250); 
        column = tblBarang.getColumnModel().getColumn(2); 
        column.setPreferredWidth(150); 
        
        cboJenis.addItem("Meja Makan");
        cboJenis.addItem("Kasur");
        cboJenis.addItem("Kursi");
        cboJenis.addItem("Lemari");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cboJenis = new javax.swing.JComboBox<>();
        btnLihat = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBarang = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        txtBahan = new javax.swing.JTextField();
        btnBeli = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtGaransi = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtKondisi = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtHarga = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Program Penjualan Mebel");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 18, 335, 67));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Pilih Jenis Barang");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 142, -1, -1));

        cboJenis.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cboJenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        cboJenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboJenisActionPerformed(evt);
            }
        });
        getContentPane().add(cboJenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 138, 196, -1));

        btnLihat.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnLihat.setText("Lihat");
        btnLihat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLihatActionPerformed(evt);
            }
        });
        getContentPane().add(btnLihat, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 196, 119, -1));

        tblBarang.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tblBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblBarang.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                tblBarangInputMethodTextChanged(evt);
            }
        });
        jScrollPane1.setViewportView(tblBarang);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 239, -1, 93));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Bahan");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 354, -1, -1));

        txtBahan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtBahan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBahanActionPerformed(evt);
            }
        });
        getContentPane().add(txtBahan, new org.netbeans.lib.awtextra.AbsoluteConstraints(329, 350, 189, -1));

        btnBeli.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnBeli.setText("Beli");
        btnBeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBeliActionPerformed(evt);
            }
        });
        getContentPane().add(btnBeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 391, 84, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Garansi Barang");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 100, -1, -1));

        txtGaransi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtGaransi, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 96, 189, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Kondisi Barang");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 142, -1, -1));

        txtKondisi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtKondisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 138, 189, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Harga ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 289, -1, -1));

        txtHarga.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 283, 189, -1));

        txtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaActionPerformed(evt);
            }
        });
        getContentPane().add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 99, 196, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Nama Pelanggan");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 100, -1, -1));

        btnExit.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnExit.setText("Kembali");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(816, 391, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboJenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboJenisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboJenisActionPerformed

    private void txtBahanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBahanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBahanActionPerformed

    private void btnLihatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLihatActionPerformed
        // TODO add your handling code here:
        String[] data = new String[3];
        a = a + 1;
        data[0] = String.valueOf(a);
        kodeJenis = (String) cboJenis.getSelectedItem();
        
        
         switch (kodeJenis) {
            case "Meja Makan":
                Jenis1 = "Kayu Jati";
                Jenis2 = "Kaca";
                Jenis3 = "Plastik";
                hargaProduk1=2000000;
                hargaProduk2=3000000;
                hargaProduk3=1000000;

            break;
            case "Kasur": {
                Jenis1 = "Kapuk";
                Jenis2 = "Busa";
                Jenis3 = "Springbed";
                hargaProduk1=1390000;
                hargaProduk2=1665000;
                hargaProduk3=1875000;
         

            break;
            }
            case "Kursi": {
                Jenis1 = "Kayu Jati";
                Jenis2 = "Plastik";
                Jenis3 = "Baja ringan";
                Jenis4 = "Rotan";
                hargaProduk1=150400;
                hargaProduk2=350000;
                hargaProduk3=213000;
                hargaProduk4=100000;

            break;
            }
            case "Lemari": {
                Jenis1 = "Kayu Jati";
                Jenis2 = "Kaca";
                Jenis3 = "Plastik";
                hargaProduk1=570000;
                hargaProduk2=390000;
                hargaProduk3=770000;

            }
             break;
        }
        
        
      
        
        data[1] = String.valueOf(Jenis1);
        data[2] = String.valueOf("Rp. "+hargaProduk1);
        penjualan.getTabel().addRow(data);

        String[] data2 = new String[3];
        a = a + 1;
        data[0] = String.valueOf(a);
        kodeJenis = (String) cboJenis.getSelectedItem();
        data[1] = String.valueOf(Jenis2);
        data[2] = String.valueOf("Rp. "+hargaProduk2);
        penjualan.getTabel().addRow(data);
        
        String[] data3 = new String[3];
        a = a + 1;
        data[0] = String.valueOf(a);
        kodeJenis = (String) cboJenis.getSelectedItem();
        data[1] = String.valueOf(Jenis3);
        data[2] = String.valueOf("Rp. "+hargaProduk3);
        penjualan.getTabel().addRow(data);
        
        String[] data4 = new String[4];
        a = a + 1;
        data[0] = String.valueOf(a);
        kodeJenis = (String) cboJenis.getSelectedItem();
        data[1] = String.valueOf(Jenis4);
        data[2] = String.valueOf("Rp. "+hargaProduk4);
        penjualan.getTabel().addRow(data);

        
        
                                           

    }//GEN-LAST:event_btnLihatActionPerformed

    private void btnBeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBeliActionPerformed
        // TODO add your handling code here:
        
                kodeBahan = String.valueOf(txtBahan.getText());
       
        
             switch (kodeBahan) {
            case "1":
                harga=hargaProduk1;
                garansi="1 tahun";
                kondisi="Baru";

            break;
            case "2": {
                harga=hargaProduk2;
                garansi="6 bulan";
                kondisi="Baru";
         

            break;
            }
            case "3": {
                harga=hargaProduk3;
                garansi="3 bulan";
                kondisi="Baru";
                
            break;
            }
            case "4": {
                harga=hargaProduk4;
                garansi="1 bulan";
                kondisi="Bekas";

            }
             break;
            }
             
        
                
                txtGaransi.setText("" + garansi);
                txtKondisi.setText("" + kondisi); 
                txtHarga.setText("Rp. " + harga);        
                
                
                
    }//GEN-LAST:event_btnBeliActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        Mulai fan = new Mulai ();
        fan.setVisible(true);
        this.setVisible(false);
        
        
    }//GEN-LAST:event_btnExitActionPerformed

    private void tblBarangInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_tblBarangInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_tblBarangInputMethodTextChanged

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame_penjualan_mebel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame_penjualan_mebel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame_penjualan_mebel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame_penjualan_mebel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame_penjualan_mebel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBeli;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnLihat;
    private javax.swing.JComboBox<String> cboJenis;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblBarang;
    private javax.swing.JTextField txtBahan;
    private javax.swing.JTextField txtGaransi;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtKondisi;
    private javax.swing.JTextField txtNama;
    // End of variables declaration//GEN-END:variables
}
